//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acreditacion
    {
        public long id { get; set; }
        public long puntoVentaId { get; set; }
        public decimal valor { get; set; }
        public Nullable<System.DateTime> fechaAcreditacion { get; set; }
    
        public virtual PuntoVenta PuntoVenta { get; set; }
    }
}
