//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemCampo = new HashSet<ItemCampo>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public int orden { get; set; }
        public bool habilitado { get; set; }
        public bool borrado { get; set; }
        public string descripcion { get; set; }
        public long proveedorId { get; set; }
        public decimal valorComision { get; set; }
        public int tipoComision { get; set; }
        public string imagen { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCampo> ItemCampo { get; set; }
    }
}
