//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCampoCatalogo
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public bool habilitado { get; set; }
        public long itemCampoId { get; set; }
    
        public virtual ItemCampo ItemCampo { get; set; }
    }
}
